### ISSUE TITLE
求webChat相关service、pojo源码

### ISSUE THREAD

**Issue by adminpass** [jkxqj/JIM#1]
本人没有用过mongoDB，可否将相关service、pojo源码发给我，谢谢！(学习使用)

**Comment by jkxqj** [comment]
加我qq 1434262447

**Comment by jkxqj** [comment]
加我qq 1434262447

**Comment by jkxqj** [comment]
欢迎加入 oldriver技术交流群 439788463

**Comment by codefan** [comment]
您好请问是否可以提供一个 可以直接部署的 LayIM的后端啊？
